// saga
export const GET_PICTURES = 'GET_PICTURES';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CREATE_NEW_PIC = 'CREATE_NEW_PIC';

// redux

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const GET_PICTURES_REQUEST = 'GET_PICTURES_REQUEST';
export const GET_PICTURES_SUCCESS = 'GET_PICTURES_SUCCESS';
export const GET_PICTURES_ERROR = 'GET_PICTURES_ERROR';

export const CREATE_NEW_PIC_REQUEST = 'CREATE_NEW_PIC_REQUEST';
export const CREATE_NEW_PIC_SUCCESS = 'CREATE_NEW_PIC_SUCCESS';
export const CREATE_NEW_PIC_ERROR = 'CREATE_NEW_PIC_ERROR';